version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    security: true
    auto_merge: true

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    security: true
    auto_merge: true

  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    security: true
    auto_merge: true

  - package-ecosystem: "pip"
    directory: "/oracle"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    security: true
    auto_merge: true
